version: "3.8"

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio_local
    hostname: minio.local
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      TZ: Asia/Bangkok
      MINIO_VOLUMES: "/data1"
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin1234
      # MINIO_SERVER_URL: "https://localhost:9000"
      # MINIO_BROWSER_REDIRECT_URL: "https://localhost:9001"
      MINIO_BROWSER_SESSION_DURATION: 1h
      MINIO_PROMETHEUS_URL: http://prometheus:9090
      MINIO_PROMETHEUS_JOB_ID: minio-job
    command: minio server  --address ":9000" --console-address ":9001" --certs-dir /etc/certs
    volumes:
      - ./data:/data1
      - ./certs:/etc/certs:ro
